### ISSUE TITLE
Installation does not fail if requirements not met

### ISSUE THREAD

**Issue by ljlamarche** [amisr/resolvedvelocities#12]
This package will successfully install even  if the packages in `requirements.txt` are not installed.  For instance,
```
pip install .
```
was sucessful, even though apexpy and tables were not installed.

This then causes import errors when attempting to run the program, requiring users to manually install packages at that point.

**Comment by ljlamarche** [comment]
@asreimer This is potentially a conda-specific problem?  Need more investigation.

**Comment by asreimer** [comment]
Yup. And whoops: https://github.com/amisr/resolvedvelocities/blob/master/setup.py#L22-L31

Those lines should not be there :)

**Comment by asreimer** [comment]
Fixed in #16, so closing.
