### ISSUE TITLE
[ENH]: Remove dependence on coord_convert.py

### ISSUE THREAD

**Issue by ljlamarche** [amisr/resolvedvelocities#5]
Currently, some of the vector plotting routines and synthetic_data.py depend on modules in coord_convert.py, which is a general purpose coordinate conversion utility.  There are 2 issues with this:
1. The only coordinate conversions that really need to be done are geodetic to ECEF and vise versa.  coord_convert.py contains many other functions that are never used.
2. coord_convert.py uses a North, East, Up ordering convention for geodetic components, which is different from the East, North, Up convention used in the rest of the code.  This makes it very easy to make mistakes that swap the East and North components of vectors.  It would be better for the code to be self-consistent throughout.

**Comment by asreimer** [comment]
I think this has been done right?

**Comment by ljlamarche** [comment]
Yep.  Closing this now.
